window_step_ms: 10
train_dir: F:\ZJU_intership\task\4\WakeWord-Studio\phase1\artifacts\models\microwakeword_qingxiaojia_300_run
features:
  - features_dir: F:\ZJU_intership\task\4\WakeWord-Studio\phase0\artifacts\features\microwakeword_smoke\positive
    sampling_weight: 1.0
    penalty_weight: 1.0
    truth: true
    truncation_strategy: truncate_start
    type: mmap
  - features_dir: F:\ZJU_intership\task\4\WakeWord-Studio\phase0\artifacts\features\microwakeword_smoke\negative
    sampling_weight: 1.0
    penalty_weight: 1.0
    truth: false
    truncation_strategy: random
    type: mmap
training_steps: [300]
positive_class_weight: [1.0]
negative_class_weight: [1.0]
learning_rates: [0.001]
batch_size: 8
time_mask_max_size: [3]
time_mask_count: [1]
freq_mask_max_size: [3]
freq_mask_count: [1]
eval_step_interval: 50
clip_duration_ms: 3000
target_minimization: 0.9
minimization_metric: null
maximization_metric: accuracy
