const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
let boot, selectedModel=null, deployModel=null, running=false, stream, context, processor, source, sendChain=Promise.resolve(), pollTimer, historyRows=[], historyFilter='ALL', falseWakeRunning=false, micAcceptanceWords=[], micAcceptanceIndex=0, micAcceptanceAttempts={};
const pageNames={generation:'数据集生成',training:'模型训练',live:'实时唤醒',deployment:'模型与部署'};

async function api(path,body){const options=body===undefined?{}:{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(body)};const response=await fetch(path,options);const data=await response.json();if(!response.ok||data.ok===false)throw new Error(data.error||`HTTP ${response.status}`);return data}
function toast(title,message=''){const el=$('#toast');el.querySelector('strong').textContent=title;el.querySelector('span').textContent=message;el.classList.add('show');clearTimeout(el._timer);el._timer=setTimeout(()=>el.classList.remove('show'),3200)}
function model(id){return boot.models.find(item=>item.id===id)}
function shortName(item){return item.name}
function modelGroups(){
  const multi=boot.models.filter(item=>item.task_type==='multi_kws'&&!item.user_imported).sort((a,b)=>({teacher_six_convmixer:0,teacher_six_bcresnet:1}[a.id]??9)-({teacher_six_convmixer:0,teacher_six_bcresnet:1}[b.id]??9));
  const binary=boot.models.filter(item=>item.task_type!=='multi_kws'&&!item.user_imported);
  const imported=boot.models.filter(item=>item.user_imported);
  return [['Multi-KWS',multi],['Binary',binary],['Imported',imported]].filter(([,items])=>items.length)
}

function initNavigation(){$$('.nav-item').forEach(button=>button.onclick=()=>{$$('.nav-item').forEach(x=>x.classList.remove('active'));button.classList.add('active');$$('.page').forEach(x=>x.classList.remove('active'));$(`#page-${button.dataset.page}`).classList.add('active');$('#page-title').textContent=pageNames[button.dataset.page]})}
function renderModels(){
  const picker=$('#live-model-select'),training=$('#train-models'),deploy=$('#deploy-models');picker.innerHTML='';training.innerHTML='';deploy.innerHTML='';
  modelGroups().forEach(([label,items])=>{const group=document.createElement('optgroup');group.label=label;items.forEach(item=>{const option=document.createElement('option');option.value=item.id;option.textContent=item.name;group.appendChild(option)});picker.appendChild(group)});
  picker.value=selectedModel;
  picker.onchange=()=>activateLiveModel(picker.value);
  boot.models.forEach(item=>{
    const train=document.createElement('div');train.className=`model-option ${item.id===selectedModel?'selected':''} ${item.trainable?'':'not-trainable'}`;train.dataset.id=item.id;train.innerHTML=`<b>${item.name}</b><small>约 ${item.size_kib.toFixed(0)} KiB · ${item.trainable?'可训练':'仅推理/部署'}</small>`;train.onclick=()=>{if(!item.trainable)return toast('该模型不可直接训练','请先注册对应 trainer 和训练配置');$$('.model-option').forEach(x=>x.classList.remove('selected'));train.classList.add('selected')};training.appendChild(train);
    const group=item.user_imported?'Imported models':item.task_type==='multi_kws'?'Multi-KWS':'Binary wake-word';
    const card=document.createElement('article');card.className=`card deploy-model-card ${item.id===deployModel?'selected':''}`;card.dataset.id=item.id;card.innerHTML=`<div class="card-title"><span>${shortName(item)}</span><span class="status-badge done">${item.active?'ACTIVE':item.status}</span></div><small>${group}</small><h3>${item.name.replace(/^Model [AB] — /,'')}</h3><p>${item.description} · ${item.format}</p><div class="model-size">${item.size_kib.toFixed(2)} <small>KiB</small></div><div class="registry-meta"><span>${item.architecture}</span><span>${item.task_type}</span><span>${item.keyword_count} keyword</span><span>${item.full_int8?'Full INT8':'TFLite'}</span><span>${item.test_available?'Test available':'No formal Test'}</span><span>${item.hardware_runtime_verified?'Runtime verified':'Runtime not verified'}</span></div>`;card.onclick=()=>selectDeployModel(item.id);deploy.appendChild(card)
  });renderLiveModel(selectedModel);selectDeployModel(deployModel)
}
function renderLiveModel(id){const item=model(id);if(!item)return;selectedModel=id;$('#live-model-select').value=id;const multi=item.task_type==='multi_kws';$('#binary-keyword-field').classList.toggle('hidden',multi);$('#multikws-vocabulary-summary').classList.toggle('hidden',!multi);$('#multikws-runtime').classList.toggle('hidden',!multi);$('#score-label').textContent=multi?'Top1 score':'Wake score';$('#live-threshold').textContent=item.threshold;$('#live-model-name').textContent=item.name.replace(/^Model [AB] — /,'');$('#live-model-id').textContent=item.id;$('#runtime-margin-threshold').textContent=Number(item.margin_threshold||0).toFixed(3);$('#runtime-task-type').textContent=multi?'Multi-KWS':'Binary';$('#runtime-architecture').textContent=item.architecture;$('#runtime-input-shape').textContent=`Input [${item.input_shape.join(',')}]`;$('#runtime-class-count').textContent=`Classes ${item.num_classes}`;$('#runtime-model-version').textContent=item.version;$('#runtime-model-sha').textContent=`SHA256 ${item.sha256||'—'}`;$('#runtime-int8').textContent=item.full_int8?'Full INT8':'TFLite';const words=item.classes||[];$('#multikws-vocabulary-summary .vocabulary-summary').textContent=multi?`${Math.max(0,item.num_classes-1)} 个提示词`:'单唤醒词';$('#live-vocabulary').innerHTML=words.length?words.map(x=>`<span>${x.display_name}</span>`).join(''):`<span>${$('#live-keyword').value}</span>`}
async function activateLiveModel(id){
  const previous=boot.active_model_id,picker=$('#live-model-select');
  if(running){picker.value=previous;return toast('监听中无法切换','请先停止监听')}
  if(id===previous){renderLiveModel(id);return}
  picker.disabled=true;
  try{await api('/api/model/activate',{model_id:id});boot=await api('/api/bootstrap');selectedModel=deployModel=boot.active_model_id;renderModels();renderState(boot.state);toast('当前模型已切换',model(selectedModel).name)}catch(error){picker.value=previous;renderLiveModel(previous);toast('模型切换失败，旧模型继续有效',error.message)}finally{picker.disabled=false}
}
function selectDeployModel(id){deployModel=id;const item=model(id);$$('.deploy-model-card').forEach(x=>x.classList.toggle('selected',x.dataset.id===id));$('#deploy-title').textContent=item.name;$('#deploy-size').textContent=`${item.size_kib.toFixed(2)} KiB`;$('#deploy-sha').textContent=item.sha256||'—'}

function renderProviders(){const select=$('#gen-provider');select.innerHTML='';boot.providers.forEach(p=>{const option=document.createElement('option');option.value=p.name;option.textContent=p.name;select.appendChild(option)});select.onchange=updateProvider;updateProvider()}
function updateProvider(){const p=boot.providers.find(x=>x.name===$('#gen-provider').value);if(!p)return;const c=p.capabilities;$('#gen-capability').textContent=c.age_metadata?'支持目录或 metadata 中的真实年龄分组':c.multi_speaker?'多说话人；无可靠年龄标签':'无可靠年龄标签';$('#gen-local-wrap').classList.toggle('hidden',!c.local_audio_import)}
function customCounts(){return{positive:Math.max(0,Number($('#custom-positive').value)||0),hard_negative:Math.max(0,Number($('#custom-hard').value)||0),negative:Math.max(0,Number($('#custom-negative').value)||0),ambient:Math.max(0,Number($('#custom-ambient').value)||0)}}
function splitCustom(targets){const totals={train:0,validation:0,test:0},ratios={train:.8,validation:.1,test:.1};Object.values(targets).forEach(count=>{const raw=Object.fromEntries(Object.entries(ratios).map(([name,ratio])=>[name,count*ratio])),parts=Object.fromEntries(Object.entries(raw).map(([name,value])=>[name,Math.floor(value)])),remaining=count-Object.values(parts).reduce((a,b)=>a+b,0),order=Object.keys(parts).sort((a,b)=>(raw[b]-parts[b])-(raw[a]-parts[a])||b.localeCompare(a));order.slice(0,remaining).forEach(name=>parts[name]++);Object.keys(totals).forEach(name=>totals[name]+=parts[name])});return totals}
function updatePlan(){const mode=$('#gen-mode').value;$('#custom-targets').classList.toggle('hidden',mode!=='自定义');const targets=mode==='自定义'?customCounts():boot.plans[mode].targets;const split=mode==='自定义'?splitCustom(targets):boot.plans[mode].split_targets,total=Object.values(targets).reduce((a,b)=>a+b,0);$('#plan-total').textContent=total.toLocaleString();$('#plan-positive').textContent=targets.positive.toLocaleString();$('#plan-hard').textContent=targets.hard_negative.toLocaleString();$('#plan-negative').textContent=targets.negative.toLocaleString();$('#plan-ambient').textContent=targets.ambient.toLocaleString();$('#plan-train').textContent=split.train.toLocaleString();$('#plan-validation').textContent=split.validation.toLocaleString();$('#plan-test').textContent=split.test.toLocaleString()}
function generationPayload(){const mode=$('#gen-mode').value;return{wake_phrase:$('#gen-keyword').value,mode,provider:$('#gen-provider').value,total:Number($('#plan-total').textContent.replaceAll(',','')),targets:mode==='自定义'?customCounts():undefined,augmentation:$('#gen-augmentation').checked,input_folder:$('#gen-input').value,output:$('#gen-output').value}}
function keywordPayload(){const source=$('#add-keyword-sources').value;return{display_name:$('#add-keyword-name').value,model_architecture:$('#add-keyword-architecture').value,positive_samples:Number($('#add-keyword-positive').value),hard_negative_samples:Number($('#add-keyword-hard').value),speech_sources:source==='both'?['kokoro','voxcpm15']:[source],augmentation:$('#add-keyword-augmentation').value,input_mode:$('#add-keyword-input-mode').value,user_wav_directory:$('#add-keyword-wav-directory').value}}

async function enumerateMics(){try{const devices=await navigator.mediaDevices.enumerateDevices(),mics=devices.filter(x=>x.kind==='audioinput'),select=$('#microphone');select.innerHTML='';mics.forEach((mic,i)=>{const option=document.createElement('option');option.value=mic.deviceId;option.textContent=mic.label||`麦克风 ${i+1}`;select.appendChild(option)});if(!mics.length)select.innerHTML='<option>使用系统默认麦克风</option>'}catch(error){$('#microphone').innerHTML='<option>点击开始时授权麦克风</option>'}}
function resample(input,from,to=16000){if(from===to)return input;const ratio=from/to,length=Math.round(input.length/ratio),output=new Float32Array(length);for(let i=0;i<length;i++){const pos=i*ratio,left=Math.floor(pos),right=Math.min(input.length-1,left+1),mix=pos-left;output[i]=input[left]*(1-mix)+input[right]*mix}return output}
function pcm16Buffer(floatData){const buffer=new ArrayBuffer(floatData.length*2),view=new DataView(buffer);for(let i=0;i<floatData.length;i++){const sample=Math.max(-1,Math.min(1,floatData[i]));view.setInt16(i*2,sample<0?sample*32768:sample*32767,true)}return buffer}
async function startListening(){
  try{const item=model(selectedModel),keyword=item.task_type==='multi_kws'?null:$('#live-keyword').value;await api('/api/live/start',{model_id:selectedModel,keyword});stream=await navigator.mediaDevices.getUserMedia({audio:{deviceId:$('#microphone').value?{exact:$('#microphone').value}:undefined,channelCount:1,echoCancellation:false,noiseSuppression:false,autoGainControl:false}});context=new AudioContext();source=context.createMediaStreamSource(stream);processor=context.createScriptProcessor(2048,1,1);processor.onaudioprocess=event=>{const down=resample(event.inputBuffer.getChannelData(0),context.sampleRate);const payload=pcm16Buffer(down);sendChain=sendChain.then(()=>fetch('/api/live/audio',{method:'POST',headers:{'Content-Type':'application/octet-stream'},body:payload})).catch(()=>{})};source.connect(processor);processor.connect(context.destination);running=true;$('#listen-toggle span:last-child').textContent='停止监听';$('#listen-toggle').classList.add('stop');$('#waveform').classList.add('active');toast('监听已开始',`${item.name} · 阈值 ${item.threshold}`);pollTimer=setInterval(pollState,120)}catch(error){await stopListening(false);toast('无法开始监听',error.message)}}
async function stopListening(show=true){if(processor){processor.disconnect();processor=null}if(source){source.disconnect();source=null}if(stream){stream.getTracks().forEach(track=>track.stop());stream=null}if(context){await context.close();context=null}running=false;clearInterval(pollTimer);try{await api('/api/live/stop',{})}catch{}$('#listen-toggle span:last-child').textContent='开始监听';$('#listen-toggle').classList.remove('stop');$('#waveform').classList.remove('active');if(show)toast('监听已停止','本次历史仍保留在页面中');await pollState()}

function boolText(value){return String(value).toLowerCase()==='true'}
function setStage(id,pass,text){const el=$(id);el.classList.toggle('pass',pass);el.querySelector('b').textContent=text}
function setLogic(id,pass,text){const el=$(id);el.classList.toggle('pass',pass);el.querySelector('small').textContent=text}
function statusCopy(status){return{STOPPED:['待机中','准备好后<br>开始监听'],IDLE:['正在监听','等待唤醒词'],SOUND:['检测到声音','正在分析<br>声音能量'],SPEECH:['检测到语音','语音输入<br>已确认'],EVALUATING:['模型识别中','正在识别<br>唤醒词'],TAIL:['尾部推理中','等待语音<br>自然结束'],WAKE:['唤醒成功','我醒来了！'],COOLDOWN:['冷却中','已完成<br>一次唤醒']}[status]||['运行中','正在处理']}
function renderState(state){
  if(state.model_id&&state.model_id!==selectedModel)renderLiveModel(state.model_id);
  const r=state.runtime,[badge,decision]=statusCopy(state.status),score=Number(r.decision_wake_score||0),threshold=Number(state.threshold);$('#hero-status').textContent=badge;$('#hero-decision').innerHTML=decision;$('#score-value').textContent=score.toFixed(3);$('#score-ring').style.setProperty('--score',`${Math.min(1,score)*360}deg`);$('#live-threshold').textContent=threshold;$('#wake-count').textContent=state.wake_count;$('#reject-count').textContent=state.reject_count;$('#playback-count').textContent=`播放 ${state.playback_count} 次`;
  const energy=Number(r.energy)>=Number(r.adaptive_threshold)&&Number(r.energy)>0,vad=!!r.vad,speech=Number(r.speech_frame_count)>=3;setStage('#stage-energy',energy,energy?'通过':'等待');setStage('#stage-vad',vad,vad?'通过':'等待');setStage('#stage-speech',speech,speech?'通过':'等待');
  const l1=String(r.l1_status).endsWith(':True'),l2=boolText(r.l2_status),l3=Number(r.cooldown)<=0,l4=boolText(r.l4_status),l5=r.l5_status==='passed';setLogic('#logic-l1',l1,l1?'通过':'等待');setLogic('#logic-l2',l2,l2?'通过':'等待');setLogic('#logic-l3',l3,l3?'通过':'冷却');setLogic('#logic-l4',l4,l4?'通过':'等待');setLogic('#logic-l5',l5,l5?'通过':r.l5_status==='pending_post_silence'?'进行中':'等待');
  const result=state.latest?.result||'IGNORE';$('#logic-result').textContent=result;$('#hero-reason').textContent=state.latest?(state.latest.result==='WAKE'?'最终 WAKE edge 已确认并进入 FIFO 播放队列':state.latest.rejection_reason):'音频始终在本地设备完成处理。';$('#tail-state').textContent=state.status==='TAIL'?`尾部推理 ${r.tail_silence_frames}/${r.tail_required_frames}`:'尚未进入尾部推理';renderHistory(state.history)
  const rejection=r.rejection_reason||'NO_NEW_SCORE',detection=r.accepted?'ACCEPTED':rejection==='NO_NEW_SCORE'?'WAITING':'REJECTED',finalKeyword=r.accepted?(r.predicted_display_name||r.predicted_keyword_id||'—'):state.latest?.result==='WAKE'?state.latest.keyword:'—';$('#runtime-top1').textContent=r.predicted_display_name||r.predicted_keyword_id||'—';$('#runtime-top1-score').textContent=Number(r.top1_score||0).toFixed(3);$('#runtime-top2').textContent=r.top2_display_name||r.top2_keyword_id||'—';$('#runtime-top2-score').textContent=Number(r.top2_score||0).toFixed(3);$('#runtime-margin').textContent=Number(r.margin||0).toFixed(3);$('#runtime-margin-threshold').textContent=Number(r.margin_threshold||0).toFixed(3);$('#runtime-background-score').textContent=Number(r.background_score||0).toFixed(3);$('#runtime-detection').textContent=detection;$('#runtime-rejection').textContent=rejection;$('#runtime-final-keyword').textContent=finalKeyword;if(!state.latest)$('#hero-reason').textContent=rejection||'音频始终在本地设备完成处理。';if(state.false_wake)$('#false-wake-status').textContent=`已观察 ${Number(state.false_wake.observed_duration_seconds).toFixed(1)} 秒 · ${state.false_wake.false_wake_count} 次 · ${Number(state.false_wake.false_wakes_per_hour).toFixed(2)} 次/小时`;
}
function renderHistory(rows){historyRows=rows;const visible=historyFilter==='ALL'?rows:rows.filter(row=>row.result===historyFilter),body=$('#history-body');if(!visible.length){body.innerHTML=`<div class="empty-state">${rows.length?'当前筛选下没有候选':'开始监听后，完成的候选会出现在这里'}</div>`;return}body.innerHTML=visible.map(row=>`<div class="history-row"><span>${row.detected_at.slice(11,19)}</span><span>${row.keyword}</span><b>${Number(row.decision_max_score).toFixed(4)}</b><span>${Number(row.threshold).toFixed(5)}</span><span class="result-pill ${row.result.toLowerCase()}">${row.result}</span><span>${row.result==='WAKE'?'已播放唤醒提示':row.rejection_reason}</span></div>`).join('')}

function fileAsBase64(file){return new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve(String(reader.result).split(',',2)[1]);reader.onerror=()=>reject(reader.error);reader.readAsDataURL(file)})}
function closeImportModal(){$('#model-import-modal').classList.add('hidden')}
function renderMicAcceptance(){const word=micAcceptanceWords[micAcceptanceIndex];if(!word){$('#mic-acceptance-target').textContent='全部完成，请保存报告';$('#mic-acceptance-progress').textContent='已完成当前词表';return}$('#mic-acceptance-target').textContent=word.display_name;$('#mic-acceptance-progress').textContent=`${micAcceptanceAttempts[word.keyword_id]||0} / 10`}
async function recordMicAcceptance(result){const word=micAcceptanceWords[micAcceptanceIndex];if(!word)return toast('当前词表已经记录完成');try{await api('/api/mic-acceptance/record',{expected_keyword_id:word.keyword_id,result});micAcceptanceAttempts[word.keyword_id]=(micAcceptanceAttempts[word.keyword_id]||0)+1;if(micAcceptanceAttempts[word.keyword_id]>=10)micAcceptanceIndex++;renderMicAcceptance()}catch(error){toast('验收记录失败',error.message)}}
async function importModel(){const file=$('#import-file').files[0];if(!file)return toast('请选择 TFLite 文件');try{$('#submit-import-model').disabled=true;const result=await api('/api/model/import',{name:$('#import-name').value,backend:$('#import-backend').value,threshold:Number($('#import-threshold').value),data_base64:await fileAsBase64(file)});boot=await api('/api/bootstrap');renderModels();closeImportModal();toast('模型导入成功',`SHA256 ${result.sha256.slice(0,16)}…`)}catch(error){toast('模型导入失败',error.message)}finally{$('#submit-import-model').disabled=false}}
async function pollState(){try{renderState(await api('/api/live/state'))}catch(error){$('#hero-status').textContent='服务断开'}}

function bindActions(){
  $('#gen-mode').onchange=updatePlan;$$('#custom-targets input').forEach(input=>input.oninput=updatePlan);$('#gen-preflight').onclick=async()=>{try{const result=await api('/api/generation/preflight',generationPayload());toast('生成配置检查通过',result.command.slice(1,3).join(' · '))}catch(error){toast('配置检查失败',error.message)}};$('#gen-start').onclick=async()=>{const payload=generationPayload();if(!confirm(`确认开始“${payload.mode}”数据生成？\n预计 ${payload.total} 条。`))return;try{await api('/api/generation/start',payload);toast('数据生成已启动','可以继续浏览其他页面')}catch(error){toast('无法启动生成',error.message)}};
  $('#train-preflight').onclick=async()=>{try{const selected=$('.model-option.selected')?.dataset.id||'model_b';await api('/api/training/preflight',{dataset:$('#train-dataset').value,model_id:selected,wake_phrase:boot.wake_phrase,output:$('#train-output').value});toast('训练配置检查通过','Test 不会被训练入口读取')}catch(error){toast('配置检查失败',error.message)}};
  $('#train-start').onclick=async()=>{const payload={dataset:$('#train-dataset').value,model_id:$('.model-option.selected')?.dataset.id||'model_b',wake_phrase:boot.wake_phrase,output:$('#train-output').value};if(!confirm('确认启动新的长时训练？\nTest 将保持冻结。'))return;try{await api('/api/training/start',payload);toast('训练已启动','页面只管理本次启动的进程')}catch(error){toast('无法启动训练',error.message)}};
  $('#listen-toggle').onclick=()=>running?stopListening():startListening();$('#inspect-model').onclick=async()=>{try{const info=await api('/api/model/inspect',{model_id:deployModel});$('#deploy-sha').textContent=info.sha256;toast('模型验证通过',`${info.kib.toFixed(2)} KiB · ${info.full_int8?'Full INT8':'量化不完整'}`)}catch(error){toast('模型验证失败',error.message)}};$('#deploy-model').onclick=async()=>{try{await api('/api/model/deploy',{model_id:deployModel,output:$('#deploy-output').value});toast('部署包已生成',$('#deploy-output').value)}catch(error){toast('部署失败',error.message)}};$('#copy-sha').onclick=async()=>{await navigator.clipboard.writeText($('#deploy-sha').textContent);toast('SHA256 已复制')}
  $$('#history-tabs button').forEach(button=>button.onclick=()=>{$$('#history-tabs button').forEach(x=>x.classList.remove('active'));button.classList.add('active');historyFilter=button.dataset.filter;renderHistory(historyRows)});$('#open-import-model').onclick=()=>$('#model-import-modal').classList.remove('hidden');$('#close-import-model').onclick=closeImportModal;$('#cancel-import-model').onclick=closeImportModal;$('#import-file').onchange=()=>$('#import-file-name').textContent=$('#import-file').files[0]?.name||'尚未选择文件';$('#submit-import-model').onclick=importModel;
  $('#add-keyword-preflight').onclick=async()=>{try{const result=await api('/api/keyword/preflight',keywordPayload());$('#add-keyword-result').textContent=JSON.stringify(result.plan,null,2);toast('计划已生成','未启动数据生成或长训练')}catch(error){toast('新增提示词预检失败',error.message)}};
  $('#add-keyword-create-job').onclick=async()=>{if(!confirm('只创建独立 job/config/命令文件，不启动数据生成或训练。继续？'))return;try{const result=await api('/api/keyword/job/create',keywordPayload());$('#add-keyword-result').textContent=JSON.stringify({job:result.job,artifacts:result.artifacts},null,2);toast('任务已创建但未启动',result.artifacts.run_dir)}catch(error){toast('任务创建失败',error.message)}};
  $('#activate-model').onclick=async()=>activateLiveModel(deployModel);
  $('#rollback-model').onclick=async()=>{try{await api('/api/model/rollback',{});boot=await api('/api/bootstrap');selectedModel=deployModel=boot.active_model_id;renderModels();renderState(boot.state);toast('已回滚',model(selectedModel).name)}catch(error){toast('无法回滚',error.message)}};
  $('#feedback-correct').onclick=async()=>{try{await api('/api/runtime/feedback',{verdict:'correct',save_audio:$('#save-error-audio').checked});toast('反馈已记录','音频保存默认关闭')}catch(error){toast('记录失败',error.message)}};
  $('#feedback-wrong').onclick=async()=>{const truth=prompt('本来应该是什么？可填 keyword_id、未说唤醒词或其它');if(truth===null)return;try{await api('/api/runtime/feedback',{verdict:'wrong',ground_truth:truth,save_audio:$('#save-error-audio').checked});toast('错误反馈已记录')}catch(error){toast('记录失败',error.message)}};
  $('#mic-acceptance-start').onclick=async()=>{try{const active=model(boot.active_model_id),words=(active.classes||[]).filter(x=>x.keyword_id!=='background');if(!words.length)return toast('当前 active model 不是 Multi-KWS');await api('/api/mic-acceptance/start',{target_attempts_per_keyword:10});micAcceptanceWords=words;micAcceptanceIndex=0;micAcceptanceAttempts={};$('#mic-acceptance-panel').classList.remove('hidden');renderMicAcceptance();toast('REAL_MIC_ACCEPTANCE 已开始','请按当前词表每词说 10 次；这不是 formal Test')}catch(error){toast('无法开始验收',error.message)}};
  $('#mic-result-correct').onclick=()=>recordMicAcceptance('correct');$('#mic-result-wrong').onclick=()=>recordMicAcceptance('wrong_keyword');$('#mic-result-rejected').onclick=()=>recordMicAcceptance('rejected');$('#mic-acceptance-finish').onclick=async()=>{try{const result=await api('/api/mic-acceptance/finish',{});$('#mic-acceptance-panel').classList.add('hidden');toast('真人验收报告已保存',result.path)}catch(error){toast('保存失败',error.message)}};
  $('#false-wake-toggle').onclick=async()=>{try{if(falseWakeRunning){const result=await api('/api/false-wake/stop',{});falseWakeRunning=false;$('#false-wake-toggle').textContent='开始背景误唤醒测试';$('#false-wake-status').textContent=`完成：${result.report.false_wake_count} 次，${Number(result.report.false_wakes_per_hour).toFixed(2)} 次/小时（不同于 Background FAR）`}else{await api('/api/false-wake/start',{});falseWakeRunning=true;$('#false-wake-toggle').textContent='停止背景误唤醒测试';toast('背景误唤醒测试已开始','建议持续 5 分钟或更久')}}catch(error){toast('操作失败',error.message)}};
}

async function init(){try{boot=await api('/api/bootstrap');selectedModel=deployModel=boot.active_model_id;$('#gen-keyword').value=boot.wake_phrase;$('#live-keyword').value=boot.wake_phrase;initNavigation();renderModels();renderProviders();updatePlan();bindActions();await enumerateMics();renderState(boot.state)}catch(error){toast('无法连接本地服务',error.message)}}
window.addEventListener('beforeunload',()=>{if(running)navigator.sendBeacon('/api/live/stop',new Blob(['{}'],{type:'application/json'}))});init();
